---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-cm
  namespace: default # Change to your gitlab namespace
data:
  entrypoint: |
    #!/bin/bash

    set -xe

    cp /scripts/config.toml /etc/gitlab-runner/

    # Register the runner
    /entrypoint register \
      --non-interactive \
      --registration-token CHANGEME \ # Insert the runner registration token here
      --url http://your.gitlab.url \
      --clone-url http://your.local.gitlab.url \ # Optional, use if gitlab is running on the same cluster
      --executor "kubernetes" \
      --name "Kubernetes Runner" \
      --config "/etc/gitlab-runner/config.toml"

    # Start the runner
    /entrypoint run --user=gitlab-runner \
      --working-directory=/home/gitlab-runner \
      --config "/etc/gitlab-runner/config.toml"
  config.toml: |
    concurrent = 10 # This sets the maximum number of concurrent CI pods
    check_interval = 10
